### ISSUE TITLE
No module named 'page' - Migrating from the deprecated web.py framework

### ISSUE THREAD

**Issue by SaadBazaz** [nirizr/argparseweb#11]
Hey there,
I first installed web.py using ```pip install web.py```, then installed this repo using ```pip install argparseweb```. 
Getting the following error during argparseweb install: 
```
Collecting argparseweb
  Using cached argparseweb-0.1.2.tar.gz (8.8 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/saadbazaz/.virtualenvs/deepdub1/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/s9/k339_45j0ygg3zls9jn91xqm0000gn/T/pip-install-enl7cjw8/argparseweb_dd594d92584743acb991194d8e03e2c9/setup.py'"'"'; __file__='"'"'/private/var/folders/s9/k339_45j0ygg3zls9jn91xqm0000gn/T/pip-install-enl7cjw8/argparseweb_dd594d92584743acb991194d8e03e2c9/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/s9/k339_45j0ygg3zls9jn91xqm0000gn/T/pip-pip-egg-info-et5r22bn
         cwd: /private/var/folders/s9/k339_45j0ygg3zls9jn91xqm0000gn/T/pip-install-enl7cjw8/argparseweb_dd594d92584743acb991194d8e03e2c9/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/s9/k339_45j0ygg3zls9jn91xqm0000gn/T/pip-install-enl7cjw8/argparseweb_dd594d92584743acb991194d8e03e2c9/setup.py", line 3, in <module>
        import argparseweb
      File "/private/var/folders/s9/k339_45j0ygg3zls9jn91xqm0000gn/T/pip-install-enl7cjw8/argparseweb_dd594d92584743acb991194d8e03e2c9/argparseweb/__init__.py", line 2, in <module>
        from .webui import *
      File "/private/var/folders/s9/k339_45j0ygg3zls9jn91xqm0000gn/T/pip-install-enl7cjw8/argparseweb_dd594d92584743acb991194d8e03e2c9/argparseweb/webui.py", line 3, in <module>
        import page
    ModuleNotFoundError: No module named 'page'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/ec/0a/cb8d85a0b3e9829f9c444f17cd4aea673c2b1e980e5a7f3e5e98eb5885aa/argparseweb-0.1.2.tar.gz#sha256=06b5775e77797d8468a5c9a0e2c5b6aa2ed534f391818b705aae1ef148244b48 (from https://pypi.org/simple/argparseweb/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement argparseweb (from versions: 0.1.2)
```

I ruled out that there's an error in finding the module "page", which is dependent on web.py. And from what I read on the Internet, web.py is deprecated. 

Are there any plans to update this repo? I have some ideas in mind, maybe they could help out.

**Comment by nirizr** [comment]
Hi, and thanks for reaching out!

I didn't touch argparseweb for over four years now and I no longer use it at all, to be honest, so I don't believe I'll spend the time required to port it to another web framework.

Feel free to either open pull requests (and I'll merge them), create a fork and maintain it over there or develop something else with similar capabilities from the ground up.

Apologies I don't have a better answer,
good luck!

**Comment by SaadBazaz** [comment]
Thanks for the response @nirizr .

I highly appreciate your effort, I'm sure this library helped many people and has completed its tenure in serving its purpose. I did some searching and stumbled upon [Wooey](https://github.com/wooey/wooey), and am using that currently for my work. I really like the idea of automatically giving beautiful webforms to CLI apps. I'll contribute in these upcoming libraries. Great work!

**Comment by nirizr** [comment]
Nice. Wooey looks like a much better tool than what I've done. I'll definitely check it out, thanks for mentioning it!
