### ISSUE TITLE
Including "%s" in argparse help text triggers help string replacement

### ISSUE THREAD

**Issue by r-chris** [nirizr/argparseweb#4]
When including `%s` in the help string for an `argparse` option, the string is being reformatted.
Example:

`parser.add_argument("-loglevel",help="%s      Logging level: None, Error, Warning, Info, Verbose, Debug or Progress [Info]",nargs=1,type=str)`

actually results in the `help` text:

`{'const': None, 'help': '%s Logging level: None, Error, Warning, Info, Verbose, Debug or Progress [Info]', 'option_strings': ['-loglevel'], 'dest': 'loglevel', 'required': False, 'nargs': 1, 'choices': None, 'default': None, 'container': <argparse._ArgumentGroup object at 0x1fac47cdaf865f>, 'type': <type 'str'>, 'metavar': None} Logging level: None, Error, Warning, Info, Verbose, Debug or Progress [Info]`

**Comment by nirizr** [comment]
I'm not sure I follow. Us this the expected behavior? Is this not expected but added when argparseweb is used?
Could you provide a small reproduction along with the expected output please?

**Comment by r-chris** [comment]
Yes, this only happens when `argparseweb` is used.
